spring.application.name=billing
server.port=8020

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html

springdoc.packagesToScan=com.paymentchain.billing.entities, com.paymentchain.billing.controller
springdoc.pathsToMatch=/v1, /billing/**